In [ ]:
import numpy as np

In [ ]:
a=np.array([2,5,6,36,78])
print(a)

[ 2  5  6 36 78]


In [ ]:
b=np.array([[4,6],[7,2]])
print(b)

[[4 6]
 [7 2]]


In [ ]:
c=a+5
print(c)

[ 7 10 11 41 83]


In [ ]:
d=a*3
print(d)

[  6  15  18 108 234]


In [ ]:
print("Mean",np.mean(a))

Mean 25.4


In [ ]:
print("sum",np.sum(a))

sum 127


In [ ]:
print("Maximum number",np.max(a))

Maximum number 78


In [ ]:
#indexing
arr=np.array([10,20,30,40])
print(arr[3])

40


In [ ]:
#slicing
print(arr[0:3])

[10 20 30]


In [ ]:
#PANDAS

In [ ]:
import pandas as pd

In [ ]:
data={
    "Name":["Aman","Riya","Chetan"],
    "Marks":[23,78,45],
    "Age":[18,17,19]
}

In [ ]:
#dataframe is the data structure used in pandas
df=pd.DataFrame(data)

In [ ]:
print(df)

     Name  Marks  Age
0    Aman     23   18
1    Riya     78   17
2  Chetan     45   19


In [ ]:
print(df.columns)

Index(['Name', 'Marks', 'Age'], dtype='object')


In [ ]:
print(df.shape)

(3, 3)


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Marks   3 non-null      int64 
 2   Age     3 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None


In [ ]:
print(df[["Name","Age"]])

     Name  Age
0    Aman   18
1    Riya   17
2  Chetan   19


In [ ]:
filtered=df[df["Marks"]<45]
print(filtered)

   Name  Marks  Age
0  Aman     23   18


In [ ]:
df["Passed"]=df["Marks"]>=45
print(df)

     Name  Marks  Age  Passed
0    Aman     23   18   False
1    Riya     78   17    True
2  Chetan     45   19    True


In [ ]:
df_sorted=df.sort_values(by="Marks",ascending=False)
print(df_sorted)

     Name  Marks  Age  Passed
1    Riya     78   17    True
2  Chetan     45   19    True
0    Aman     23   18   False


In [ ]:
df.iloc[0]

,0
Name,Aman
Marks,23
Age,18
Passed,False
